"""
Training data generation for comment classifier.

This module provides utilities for generating labeled training data
from codebase comments.
"""

import os
from pathlib import Path
from typing import List, Tuple, Set, Dict, Any
from dataclasses import dataclass, field

from .patterns import MISLEADING_PATTERNS, ACCURATE_PATTERNS, EXCLUDE_PATTERNS
from .scanner import find_python_files, extract_comments_from_file
from .classifier import should_exclude, classify_comment


@dataclass
class TrainingStats:
    """Statistics from training data generation."""
    total_comments: int = 0
    excluded: int = 0
    misleading: int = 0
    accurate: int = 0
    unknown: int = 0
    by_pattern: Dict[str, int] = field(default_factory=dict)


@dataclass
class TrainingData:
    """Generated training data."""
    misleading: List[str]
    accurate: List[str]
    stats: TrainingStats


def generate_training_data(
    directories: List[str],
    max_per_class: int = 50,
    min_comment_length: int = 4,
    verbose: bool = False,
) -> TrainingData:
    """
    Generate training data by extracting and classifying comments.

    Args:
        directories: List of directories to scan
        max_per_class: Maximum examples per class
        min_comment_length: Minimum comment length to consider
        verbose: Print progress information

    Returns:
        TrainingData with classified comments and statistics
    """
    misleading: List[str] = []
    accurate: List[str] = []
    seen: Set[str] = set()
    stats = TrainingStats()

    for directory in directories:
        if not os.path.isdir(directory):
            if verbose:
                print(f"Warning: Directory not found: {directory}")
            continue

        python_files = find_python_files(directory)
        if verbose:
            print(f"Scanning {len(python_files)} Python files in {directory}...")

        for file_path in python_files:
            comments = extract_comments_from_file(file_path)

            for line_num, comment in comments:
                stats.total_comments += 1

                # Skip short comments
                if len(comment) <= min_comment_length:
                    stats.excluded += 1
                    continue

                # Skip excluded patterns (noise)
                if should_exclude(comment):
                    stats.excluded += 1
                    continue

                # Skip duplicates
                comment_normalized = comment.lower().strip()
                if comment_normalized in seen:
                    continue
                seen.add(comment_normalized)

                # Classify
                result = classify_comment(comment)

                if result.classification == 'misleading' and len(misleading) < max_per_class:
                    misleading.append(comment)
                    stats.misleading += 1
                    stats.by_pattern[result.pattern_type] = \
                        stats.by_pattern.get(result.pattern_type, 0) + 1
                    if verbose:
                        print(f"  [MISLEADING] {file_path}:{line_num}")

                elif result.classification == 'accurate' and len(accurate) < max_per_class:
                    accurate.append(comment)
                    stats.accurate += 1
                    stats.by_pattern[result.pattern_type] = \
                        stats.by_pattern.get(result.pattern_type, 0) + 1
                    if verbose:
                        print(f"  [ACCURATE] {file_path}:{line_num}")

                else:
                    stats.unknown += 1

    # Deduplicate final lists (preserve order)
    misleading = list(dict.fromkeys(misleading))[:max_per_class]
    accurate = list(dict.fromkeys(accurate))[:max_per_class]

    return TrainingData(
        misleading=misleading,
        accurate=accurate,
        stats=stats,
    )


def write_training_files(
    data: TrainingData,
    output_dir: Path,
    generator_command: str = "python scripts/audit_tool.py generate",
) -> Tuple[Path, Path]:
    """
    Write training data to files.

    Args:
        data: Training data to write
        output_dir: Output directory
        generator_command: Command used to generate (for header comment)

    Returns:
        Tuple of (misleading_file_path, accurate_file_path)
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write misleading.txt
    misleading_file = output_dir / "misleading.txt"
    with open(misleading_file, 'w', encoding='utf-8') as f:
        f.write("# Misleading comments - speculative, outdated, or referencing non-existent resources\n")
        f.write(f"# Auto-generated by: {generator_command}\n")
        f.write("# One comment per line\n\n")
        for comment in data.misleading:
            f.write(comment.strip() + "\n")

    # Write accurate.txt
    accurate_file = output_dir / "accurate.txt"
    with open(accurate_file, 'w', encoding='utf-8') as f:
        f.write("# Accurate comments - factual descriptions, valid documentation\n")
        f.write(f"# Auto-generated by: {generator_command}\n")
        f.write("# One comment per line\n\n")
        for comment in data.accurate:
            f.write(comment.strip() + "\n")

    print(f"\nWrote {len(data.misleading)} examples to {misleading_file}")
    print(f"Wrote {len(data.accurate)} examples to {accurate_file}")

    return misleading_file, accurate_file


def load_training_files(
    training_dir: Path,
) -> 'TrainingData | None':
    """
    Load training data from files.

    Args:
        training_dir: Directory containing misleading.txt and accurate.txt

    Returns:
        TrainingData with loaded comments, or None if files don't exist
    """
    misleading_file = training_dir / "misleading.txt"
    accurate_file = training_dir / "accurate.txt"

    if not misleading_file.exists() or not accurate_file.exists():
        return None

    misleading = []
    with open(misleading_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                misleading.append(line)

    accurate = []
    with open(accurate_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                accurate.append(line)

    # Create minimal stats for loaded data
    stats = TrainingStats(
        total_comments=len(misleading) + len(accurate),
        misleading=len(misleading),
        accurate=len(accurate),
    )

    return TrainingData(
        misleading=misleading,
        accurate=accurate,
        stats=stats,
    )
